server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKE:localhost:9092}
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest

#desabilitar os logs que o kafka exibe
logging:
  level:
    org:
      apache:
        kafka: OFF